$( out-of-range-saved-step-bad1.mm
   Incorrect compressed proof: An example generated by ChatGPT o3
   That references a proof index greater than the number of saved proof steps.
   Added because mmverify.py was missing a raise MMError and tests did not flag it. $)

$c |- T $.

ax     $a |- T $.
buggy  $p |- T $= ( ax ) A Z C $.