$( Minimal test: compressed proof with essential hypotheses AND Z marker $)
$( Based on demo0.mm structure - tests the combination that fails in big-unifier.mm $)
$(
  This test case is designed to isolate the bug where:
  - Compressed proofs work (test57 passes)
  - Normal proofs with e-hyps work (demo0.mm passes)
  - BUT compressed proofs with e-hyps + Z marker FAIL (big-unifier.mm fails)

  This file contains both normal and compressed versions of the same proof,
  allowing direct comparison of verification behavior.
$)

$c 0 + = -> ( ) term wff |- $.
$v t r s P Q $.

tt $f term t $.
tr $f term r $.
ts $f term s $.
wp $f wff P $.
wq $f wff Q $.

$( Define term $)
tze $a term 0 $.
tpl $a term ( t + r ) $.

$( Define wff $)
weq $a wff t = r $.
wim $a wff ( P -> Q ) $.

$( Axioms $)
a1 $a |- ( t = r -> ( t = s -> r = s ) ) $.
a2 $a |- ( t + 0 ) = t $.

$( Modus ponens - has essential hypotheses $)
${
  min $e |- P $.
  maj $e |- ( P -> Q ) $.
  mp $a |- Q $.
$}

$( Normal proof of |- t = t - should work $)
th1_normal $p |- t = t $=
  tt tze tpl tt weq tt tt weq tt a2 tt tze tpl tt weq tt tze tpl tt weq tt tt
  weq wim tt a2 tt tze tpl tt tt a1 mp mp $.

$(
  Compressed proof of |- t = t generated by Metamath program.
  This proof:
  1. Uses compressed format
  2. Uses modus ponens (mp) which has essential hypotheses
  3. Uses Z marker to save/recall intermediate results

  Labels:
    A=tt (mandatory f-hyp)
    B=tze, C=tpl, D=weq, E=a2, F=wim, G=a1, H=mp (explicit labels)

  Proof string: ABCZADZAADZAEZJJKFLIAAGHH

  The Z at position 4 saves something, then J (index 9) recalls it.
  This combines all three ingredients that cause big-unifier.mm to fail.
$)
th1_compressed $p |- t = t $=
  ( tze tpl weq a2 wim a1 mp ) ABCZADZAADZAEZJJKFLIAAGHH $.

